title: Skylar's Personal Blog
author: A GitHub User
email: skylar@tdavis.me
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my personal blog website. I'm very exited to list to list my resume and project details on my personal
  website. I wanted to create a personal page from scratch to get the experience. Creating a webpage from 
  scratch is about the experience in learning something new. Thank you for visiting my webpage today. 

# social links
twitter_username: Not on twitter or social media yet.  # DO NOT include the @ character, or else the build will fail!
github_username:  sd262b # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
